language: ruby

cache: bundler

rvm:
  - 2.1.2
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - jruby-19mode
  - ruby-head
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-2.2.10
